---
abstract: 'Allow roles to modify attributes'
author:
  - 'Edward Allen <ealleniii_at_cpan_dot_org>'
build_requires:
  TAP::Harness: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-Role-AttributeOverride
provides:
  MooseX::Role::AttributeOverride:
    file: lib/MooseX/Role/AttributeOverride.pm
    version: v0.0.3
  MooseX::Role::AttributeOverride::Meta::Trait::Role:
    file: lib/MooseX/Role/AttributeOverride/Meta/Trait/Role.pm
    version: v0.0.3
  MooseX::Role::AttributeOverride::Meta::Trait::Role::ApplicationToClass:
    file: lib/MooseX/Role/AttributeOverride/Meta/Trait/Role/ApplicationToClass.pm
    version: v0.0.3
  MooseX::Role::AttributeOverride::Meta::Trait::Role::ApplicationToRole:
    file: lib/MooseX/Role/AttributeOverride/Meta/Trait/Role/ApplicationToRole.pm
    version: v0.0.3
  MooseX::Role::AttributeOverride::Meta::Trait::Role::Composite:
    file: lib/MooseX/Role/AttributeOverride/Meta/Trait/Role/Composite.pm
    version: v0.0.3
requires:
  Moose: 1.99
  version: 0.77
resources:
  license: http://dev.perl.org/licenses/
version: v0.0.3
